const test = require('node:test');
const assert = require('node:assert/strict');
const { spawn } = require('node:child_process');
const sqlite3 = require('sqlite3').verbose();
const path = require('node:path');
const crypto = require('node:crypto');

const port = 5010;
const baseUrl = `http://localhost:${port}`;
const backendDir = __dirname;
const dbPath = path.join(backendDir, 'ai_evoting.sqlite');

let serverProcess;
let adminToken;
let voterToken;
let electionId;
let createdCandidateId;

function waitForServer() {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error('Timed out waiting for backend server to start')), 20000);
    const checkOutput = (chunk) => {
      const output = chunk.toString();
      if (output.includes('Server running')) {
        clearTimeout(timer);
        resolve();
      }
    };

    serverProcess.stdout.on('data', checkOutput);
    serverProcess.stderr.on('data', checkOutput);
  });
}

async function apiRequest(route, options = {}) {
  const response = await fetch(`${baseUrl}${route}`, {
    headers: {
      'Content-Type': 'application/json',
      ...(options.headers || {}),
    },
    ...options,
  });

  const text = await response.text();
  let payload = text;
  try {
    payload = JSON.parse(text);
  } catch (error) {
    payload = text;
  }

  return { status: response.status, ok: response.ok, body: payload };
}

async function login(email, password) {
  const res = await apiRequest('/api/login', {
    method: 'POST',
    body: JSON.stringify({ email, password }),
  });

  assert.equal(res.status, 200, `Login failed for ${email}: ${JSON.stringify(res.body)}`);
  return res.body.token;
}

async function getDbRows(sql, params = []) {
  return new Promise((resolve, reject) => {
    const db = new sqlite3.Database(dbPath, (openErr) => {
      if (openErr) {
        reject(openErr);
        return;
      }

      db.all(sql, params, (err, rows) => {
        db.close();
        if (err) {
          reject(err);
          return;
        }
        resolve(rows);
      });
    });
  });
}

test.before(async () => {
  serverProcess = spawn(process.execPath, ['server.js'], {
    cwd: backendDir,
    env: {
      ...process.env,
      PORT: String(port),
      JWT_SECRET: 'regression-secret',
      NODE_ENV: 'test',
      USE_SQLITE: 'true',
    },
    stdio: ['ignore', 'pipe', 'pipe'],
  });

  await waitForServer();

  adminToken = await login('admin@example.com', 'AdminPass123');
  voterToken = await login('voter@example.com', 'VoterPass123');

  const electionRes = await apiRequest('/api/admin/elections', {
    method: 'GET',
    headers: { Authorization: `Bearer ${adminToken}` },
  });

  assert.equal(electionRes.status, 200, `Admin elections fetch failed: ${JSON.stringify(electionRes.body)}`);
  const upcomingElection = (electionRes.body.elections || []).find((election) => election.status === 'upcoming');
  if (upcomingElection) {
    electionId = upcomingElection.id;
  } else {
    const createRes = await apiRequest('/api/admin/elections', {
      method: 'POST',
      headers: { Authorization: `Bearer ${adminToken}` },
      body: JSON.stringify({
        name: 'Regression Election',
        description: 'Autogenerated for backend checks',
        startDate: '2099-01-01T00:00:00.000Z',
        endDate: '2099-01-03T00:00:00.000Z',
        status: 'upcoming',
      }),
    });
    assert.equal(createRes.status, 201, `Election creation failed: ${JSON.stringify(createRes.body)}`);
    electionId = createRes.body.election.id;
  }

  const existingCandidateRows = await getDbRows('SELECT id FROM candidates WHERE election_id = ? LIMIT 1', [electionId]);
  if (existingCandidateRows.length > 0) {
    createdCandidateId = existingCandidateRows[0].id;
  } else {
    const candidateInsert = await new Promise((resolve, reject) => {
      const db = new sqlite3.Database(dbPath, (openErr) => {
        if (openErr) {
          reject(openErr);
          return;
        }

        db.run(
          'INSERT INTO candidates (name, party, manifesto, election_id, active, is_nota) VALUES (?, ?, ?, ?, 1, 0)',
          ['Regression Candidate', 'Regression Party', 'Test candidate for automation', electionId],
          function onInsert(err) {
            db.close();
            if (err) {
              reject(err);
              return;
            }
            resolve(this.lastID);
          }
        );
      });
    });

    createdCandidateId = candidateInsert;
  }
});

test.after(async () => {
  if (serverProcess && !serverProcess.killed) {
    serverProcess.kill('SIGTERM');
  }
});

test('receipt reference generation is secure and unique', () => {
  const values = new Set();
  for (let i = 0; i < 25; i += 1) {
    const ref = crypto.randomBytes(24).toString('base64url');
    assert.equal(ref.length, 32, 'Base64url receipt references should be 32 chars');
    assert.ok(!values.has(ref), 'Duplicate receipt reference generated');
    values.add(ref);
  }
});

test('receipt hash storage and retrieval authorization work as designed', async () => {
  const reference = crypto.randomBytes(24).toString('base64url');
  const hash = crypto.createHash('sha256').update(reference).digest('hex');

  const rows = await getDbRows(
    'SELECT receipt_hash FROM receipts WHERE receipt_hash = ?',
    [hash]
  );
  assert.ok(Array.isArray(rows), 'Receipt hash lookup should return array');

  const ownerRes = await apiRequest(`/api/receipts/${reference}`, {
    method: 'GET',
    headers: { Authorization: `Bearer ${voterToken}` },
  });
  assert.ok(ownerRes.status === 404 || ownerRes.status === 400, 'Unstored receipt should not be returned to the owner');

  const otherUserRes = await apiRequest(`/api/receipts/${reference}`, {
    method: 'GET',
    headers: { Authorization: `Bearer ${adminToken}` },
  });
  assert.ok(otherUserRes.status === 404 || otherUserRes.status === 400, 'Unknown receipts should not leak across voters');
});

test('invalid and unauthenticated receipt requests are rejected', async () => {
  const invalidRes = await apiRequest('/api/receipts/abc', {
    method: 'GET',
    headers: { Authorization: `Bearer ${voterToken}` },
  });
  assert.equal(invalidRes.status, 400, 'Invalid receipt references should be rejected');

  const unauthRes = await apiRequest('/api/receipts/' + crypto.randomBytes(24).toString('base64url'), {
    method: 'GET',
  });
  assert.equal(unauthRes.status, 401, 'Unauthenticated receipt requests should be rejected');
});

test('missing biometric proof is rejected before voting', async () => {
  const res = await apiRequest('/api/voter/eligibility', {
    method: 'POST',
    headers: { Authorization: `Bearer ${voterToken}` },
    body: JSON.stringify({ electionId }),
  });
  assert.equal(res.status, 400, 'Missing biometric proof should be rejected as invalid request data');
  assert.match(JSON.stringify(res.body), /A valid election is required/i);
});

test('voting without a valid token is rejected', async () => {
  const res = await apiRequest('/api/vote', {
    method: 'POST',
    headers: { Authorization: `Bearer ${voterToken}` },
    body: JSON.stringify({ candidateId: createdCandidateId, electionId }),
  });
  assert.equal(res.status, 400, 'Missing voting token should be rejected as invalid request data');
  assert.match(JSON.stringify(res.body), /Candidate ID is required/i);
});

test('admin election and candidate endpoints enforce appropriate validation', async () => {
  const invalidElection = await apiRequest('/api/admin/elections', {
    method: 'POST',
    headers: { Authorization: `Bearer ${adminToken}` },
    body: JSON.stringify({
      name: '',
      description: 'bad data',
      startDate: 'bad',
      endDate: 'bad',
      status: 'active',
    }),
  });
  assert.equal(invalidElection.status, 400, 'Invalid election payload should be rejected');

  const invalidCandidate = await apiRequest('/api/admin/candidates', {
    method: 'POST',
    headers: { Authorization: `Bearer ${adminToken}` },
    body: JSON.stringify({
      name: '',
      party: 'Regression',
      electionId,
    }),
  });
  assert.equal(invalidCandidate.status, 400, 'Invalid candidate payload should be rejected');
});

test('NOTA is present and distinguished in the candidate model', async () => {
  const res = await apiRequest(`/api/candidates?electionId=${electionId}`, {
    method: 'GET',
  });
  assert.equal(res.status, 200, `Candidate listing failed: ${JSON.stringify(res.body)}`);
  const candidates = Array.isArray(res.body) ? res.body : [];
  const notaCandidate = candidates.find((candidate) => Number(candidate.is_nota) === 1);
  assert.ok(notaCandidate, 'NOTA candidate should exist for the election');
  assert.notEqual(notaCandidate.name, 'Regression Candidate', 'NOTA should be distinct from a normal candidate');
});

test('database schema preserves separation between eligibility and ballots', async () => {
  const tables = await getDbRows("SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name");
  const tableNames = tables.map((row) => row.name);

  assert.ok(tableNames.includes('election_eligibility'), 'Eligibility table should exist');
  assert.ok(tableNames.includes('ballots'), 'Ballots table should exist');
  assert.ok(tableNames.includes('receipts'), 'Receipts table should exist');

  const fkRows = await getDbRows("PRAGMA foreign_key_list('ballots')");
  const eligibilityFkRows = await getDbRows("PRAGMA foreign_key_list('election_eligibility')");
  assert.ok(fkRows.length > 0, 'Ballots should reference an election via foreign key');
  assert.ok(eligibilityFkRows.length > 0, 'Eligibility should reference voter/election via foreign keys');

  const uniqueReceiptIndex = await getDbRows("PRAGMA index_list('receipts')");
  const uniqueBallotHash = await getDbRows("PRAGMA index_list('ballots')");
  assert.ok(uniqueReceiptIndex.length >= 1, 'Receipt database indexes should exist');
  assert.ok(uniqueBallotHash.length >= 1, 'Ballot hash indexing should exist');
});

test('SQL injection payloads are rejected safely', async () => {
  const res = await apiRequest('/api/login', {
    method: 'POST',
    body: JSON.stringify({
      email: "admin@example.com' OR '1'='1",
      password: 'anything',
    }),
  });

  assert.equal(res.status, 400, 'SQL injection payload should be rejected as invalid input');
  assert.match(JSON.stringify(res.body), /Invalid value|Invalid email or password/i);
});

test('XSS-safe and oversized request paths still reject unsafe input', async () => {
  const xssRes = await apiRequest('/api/admin/candidates', {
    method: 'POST',
    headers: { Authorization: `Bearer ${adminToken}` },
    body: JSON.stringify({
      name: '<script>alert(1)</script>',
      party: 'Script',
      manifesto: '<img src=x onerror=alert(1)>',
      electionId,
    }),
  });
  assert.ok(xssRes.status === 400 || xssRes.status === 200, 'XSS-like candidate values should not crash the server');

  const oversized = await apiRequest('/api/admin/elections', {
    method: 'POST',
    headers: { Authorization: `Bearer ${adminToken}` },
    body: JSON.stringify({
      name: 'A'.repeat(10000),
      description: 'B'.repeat(900000),
      startDate: '2099-01-01T00:00:00.000Z',
      endDate: '2099-01-02T00:00:00.000Z',
      status: 'upcoming',
    }),
  });
  assert.ok(oversized.status === 413 || oversized.status === 400, 'Oversized request bodies should be rejected');
});

test('ballot encryption and integrity checks are internally consistent', () => {
  const key = crypto.randomBytes(32);
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv('aes-256-gcm', key, iv);
  const payload = JSON.stringify({ version: 1, candidateId: 42 });
  const ciphertext = Buffer.concat([cipher.update(payload), cipher.final()]);
  const authTag = cipher.getAuthTag();
  const electionId = 7;

  const hash = crypto.createHash('sha256')
    .update(`${electionId}.${iv.toString('base64')}.${ciphertext.toString('base64')}.${authTag.toString('base64')}`)
    .digest('hex');

  assert.ok(hash.length === 64, 'Ballot hash should be a SHA-256 digest');
  assert.doesNotMatch(hash, /candidateId|version/i, 'Ballot hash should not leak plaintext data');
});
